# NumPy 
NumPy is known as the numerical python

**working with the numbers / importantly on arrays**

- numpy is stands for numerical python
- in this consisting of multidimentional array objects and collecton for processing those arrays
- using Numpy mathmatical and logical operations on array can be performed
- for more information we can go with **numpy.org** website 


In [2]:
import numpy

a1=numpy.array([1,2,3])

In [4]:
a1.ndim

1

In [3]:
print(a1)

[1 2 3]


In [4]:
print(a1.max())

3


In [6]:
print(type(a1))

<class 'numpy.ndarray'>


In [3]:
import numpy as np
a2=np.array([[1,2,3],[4,5,6]])


In [6]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
a3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(a3.ndim)

2


## Various built in functions

In [18]:
print(a3.ndim)

2


In [9]:
a4=np.zeros(5)
a4

array([0., 0., 0., 0., 0.])

In [10]:
a4=np.empty(10)
a4

array([1.21500196e-311, 2.37151510e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16096346e-028, 1.04857803e-142, 1.16467185e-028,
       1.96849090e-062, 8.45915178e-053])

In [11]:
a4=np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a4=np.arange(10,0,-1)
a4

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
a4=np.arange(1,11)
a4


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
b=a4.reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### difference bitween resize and reshape 
- reshape only gives the output as new dimensional array but does not changes the orginal array 
- resize changes the orginal array to new dimensional array 


In [16]:
c=a4.resize(1,10)
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [17]:
d=np.arange(10).reshape(2,5)
d


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a=np.array([1,2,3,4])
b=np.array([9,5,6,7])
print(a)
print(b)
c=a+b
c

[1 2 3 4]
[9 5 6 7]


array([10,  7,  9, 11])

In [12]:
a.resize(2,2)
b.resize(2,2)
print(a)
print(b)
x=a*b
print(x)
print(x.ndim)

[[1 2]
 [3 4]]
[[9 5]
 [6 7]]
[[ 9 10]
 [18 28]]
2


In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [37]:
np.sum(a,axis=0)


array([4, 6])

In [39]:
np.sum(a,axis=1)

array([3, 7])

In [6]:
c=np.array([1,2,3,4])
sum(c)

10

In [9]:
np.mean(c)
b=np.array([7,8,9,10])

In [48]:
d=np.concatenate((b,c),axis=0)
d


array([ 7,  8,  9, 10,  1,  2,  3,  4])

In [49]:
np.unique(d)

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [19]:
y=np.ones((2,3),dtype=int)
y

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
x=np.zeros((2,4),dtype=int)
x


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])